[behave]
# Output formats - can specify multiple
format = pretty



# Other settings
show_timings = True
show_source = True
color = True

# Tags to skip by default
default_tags = -@wip -@skip

# Logging
log_capture = True
logging_level = INFO
logging_format = %(asctime)s - %(levelname)s - %(message)s